# Generated by Django 5.1.2 on 2024-10-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urlshort", "0004_alter_shorturl_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="is_enable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="shorturl",
            name="url",
            field=models.URLField(max_length=700),
        ),
    ]
